### ISSUE TITLE
这个库支持CharacterGLM吗？

### ISSUE THREAD

**Issue by hongmaoxiao** [blastZ/pkg-universe#2]
您好，请问这个库支持CharacterGLM吗？

**Comment by blastZ** [comment]
`packages/zhipuai` 只封装了 ChatGLM，你可以 Fork 后，增加新的 model 支持，接口基本没差别，稍加改动就能使用

**Comment by blastZ** [comment]
`zhipuai@1.0.0` 已新增 CharacterGLM 和 ChatGLMTurbo 支持
